### ISSUE TITLE
Missing dependencies for tdd

### ISSUE THREAD

**Issue by yatesco** [rintoj/react-ts#3]
Steps:
1. fresh install of `react-ts`
2. `react-ts create todo`
3. `yarn install`
4. `yarn run tdd`

Fails with:

```
> yarn run tdd
yarn run v0.24.4
$ concurrently -r 'npm run watch' 'npm run test:watch' 
sh: concurrently: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

5. `yarn add concurrently`
6. `yarn run tdd` fails due to missing `nodemon`
7. `yarn add nodemon`
6. `yarn run tdd` works as expected

**Comment by rintoj** [comment]
Thanks for reporting this. fixed with version 2.0.2
